/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import apoio.Formatacao;
import apoio.PDFManager;
import controller.ControlaSafra;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import model.Safra;

/**
 *
 * @author henrique
 */
public class CadastroSafra extends javax.swing.JInternalFrame {
    
    
    ControlaSafra cs = new ControlaSafra();
    int codigo = 0;    
;
    /**ã
     * Creates new form CadastroSafra
     */
    public CadastroSafra() {
        initComponents();
        montaTabela();
        Formatacao.formatarData(cxDataInicio);
        Formatacao.formatarData(cxDataFim);
        

    }
    
    private void montaTabela() {
    ArrayList<Safra> s = cs.recuperarTodos();
        if (s == null) {
            System.out.println("Ocorreu um erro ao consultar as tarefas");
        } else {
        tblSafra.setModel(new AbstractTableModel() {
                @Override
                public String getColumnName(int column) {
                    switch (column) {
                        case 0:
                            return "ID";
                        case 1:
                            return "Nome";
                        case 2:
                            return "Descrição";
                        case 3:
                            return "Data de Inicio";
                        case 4:
                            return "Data de Fim";
                        default:
                            return "";
                    }
                }

                @Override
                public int getColumnCount() {
                    return 5;
                }

                @Override
                public int getRowCount() {
                    return s.size();
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Safra t = s.get(rowIndex);

                    if (t != null) {
                        switch (columnIndex) {
                            case 0:
                                return t.getId();
                            case 1:
                                return t.getNome();
                            case 2:
                                return t.getDescricao();
                            case 3:
                                return t.getDataInicio();
                            case 4:
                                return t.getDataFim();
                        }

                    }

                    return "n/d";
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tabela = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        cxDataInicio = new javax.swing.JFormattedTextField();
        cxDataFim = new javax.swing.JFormattedTextField();
        cxNome = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        cxDescricao = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSafra = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        bntEditar = new javax.swing.JButton();
        bntPDF = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        jLabel1.setText("jLabel1");

        setClosable(true);
        setTitle("Cadastro de Safra");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nome *");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel3.setText("Descrição");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setText("Data de Inicio *");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel5.setText("Data de fim (extimativa) *");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jButton1.setText("Salvar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 432, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 670, -1));

        jLabel6.setText("(*) Itens Obrigatórios");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 435, -1, -1));

        cxDataInicio.addActionListener(this::cxDataInicioActionPerformed);
        jPanel1.add(cxDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 210, -1));
        jPanel1.add(cxDataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 210, -1));
        jPanel1.add(cxNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 540, -1));

        cxDescricao.setColumns(20);
        cxDescricao.setRows(5);
        jScrollPane1.setViewportView(cxDescricao);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 540, -1));

        tabela.addTab("Safra", jPanel1);

        tblSafra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblSafra);

        jButton3.setText("Atualizar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(this::bntExcluirActionPerformed);

        bntEditar.setText("Editar");
        bntEditar.addActionListener(this::bntEditarActionPerformed);

        bntPDF.setText("Exportar PDF");
        bntPDF.addActionListener(this::bntPDFActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bntExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntPDF)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(bntEditar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntPDF)
                    .addComponent(jButton3)
                    .addComponent(bntEditar)
                    .addComponent(bntExcluir))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tabela.addTab("Tabela de Safras", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 636, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabela, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome = cxNome.getText();
        String descricao = cxDescricao.getText();
        String dataInicio = cxDataInicio.getText();
        String dataFim = cxDataFim.getText();

        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nome é obrigatório!");
            return;
        }
        if (dataInicio.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data de Início é obrigatória!");
            return;
        }
        if (dataFim.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data de Fim é obrigatória!");
            return;
        }

        Safra s = new Safra();
        s.setNome(nome);
        s.setDescricao(descricao);
        s.setDataInicio(Formatacao.ajustaDataAMD(dataInicio));
        s.setDataFim(Formatacao.ajustaDataAMD(dataFim));

        boolean retorno;
        if (codigo > 0) {
            s.setId(codigo);
            retorno = cs.editar(s);
            if (retorno) JOptionPane.showMessageDialog(null, "Editado com sucesso");
            else JOptionPane.showMessageDialog(null, "Ocorreu um erro, verifique os logs.");
            codigo = 0;
        } else {
            retorno = cs.salvar(s);
            if (retorno) JOptionPane.showMessageDialog(null, "Salvo com sucesso");
            else JOptionPane.showMessageDialog(null, "Ocorreu um erro, verifique os logs.");
        }

        cxNome.setText("");
        cxDescricao.setText("");
        cxDataInicio.setText("");
        cxDataFim.setText("");
        cxNome.requestFocus();
        montaTabela();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        montaTabela();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        String idString = String.valueOf(tblSafra.getValueAt(tblSafra.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);

        boolean retorno = cs.excluir(id);
        if (retorno) {
            JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
            montaTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao excluir!");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        String idString = String.valueOf(tblSafra.getValueAt(tblSafra.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);

        Safra s = cs.recuperarUm(id);
        if (s != null) {
            codigo = s.getId();
            
            tabela.setSelectedIndex(0);
            cxNome.setText(s.getNome());
            cxDescricao.setText(s.getDescricao());
            cxDataInicio.setText(Formatacao.ajustaDataDMA(s.getDataInicio()));
            cxDataFim.setText(Formatacao.ajustaDataDMA(s.getDataFim()));
            
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao editar!");
        }
    }//GEN-LAST:event_bntEditarActionPerformed

    private void bntPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPDFActionPerformed
        ArrayList<Safra> s = cs.recuperarTodos();
        try {
            PDFManager.gerar(s, "safra.pdf");} 
        
        catch (IOException ex) {
            System.getLogger(CadastroSafra.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_bntPDFActionPerformed

    private void cxDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxDataInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntPDF;
    private javax.swing.JFormattedTextField cxDataFim;
    private javax.swing.JFormattedTextField cxDataInicio;
    private javax.swing.JTextArea cxDescricao;
    private javax.swing.JFormattedTextField cxNome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTabbedPane tabela;
    private javax.swing.JTable tblSafra;
    // End of variables declaration//GEN-END:variables
}
