/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import controller.ControlaCusto;
import entidades.DAO.CombosDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import model.ComboItem;
import model.Custo;
import model.Producao;
import model.TipoCusto;

/**
 *
 * @author henrique
 */
public class CadastroCusto extends javax.swing.JInternalFrame {
    
    ControlaCusto cc = new ControlaCusto();

    int codigo = 0;

    /**
     * Creates new form CadastroCusto
     */
    public CadastroCusto() {
        initComponents();
        popularCombos();
        montaTabela();


    }
    
    private void popularCombos() {
        CombosDAO dao = new CombosDAO();
        dao.popularCombo("producao", "id_producao", "data_inicio", comboProducao, "");
        dao.popularCombo("tipo_custo", comboTipoCusto);
    }

    private void montaTabela() {
    ArrayList<Custo> c = cc.recuperarTodos();
        if (c == null) {
            System.out.println("Ocorreu um erro ao consultar as tarefas");
        } else {
        tblCusto.setModel(new AbstractTableModel() {
                @Override
                public String getColumnName(int column) {
                    switch (column) {
                        case 0:
                            return "ID Custo";
                        case 1:
                            return "ID Prdocução";
                        case 2:
                            return "ID Tipo de Custo";
                        case 3:
                            return "Valor";
                        default:
                            return "";
                    }
                }

                @Override
                public int getColumnCount() {
                    return 4;
                }

                @Override
                public int getRowCount() {
                    return c.size();
                }

                @Override
                public Object getValueAt(int rowIndex, int columnIndex) {
                    Custo t = c.get(rowIndex);

                    if (t != null) {
                        switch (columnIndex) {
                            case 0:
                                return t.getId();
                            case 1:
                                return t.getProducao().getId();
                            case 2:
                                return t.getTipoCusto().getId();
                            case 3:
                                return t.getValor();
                        }

                    }

                    return "n/d";
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        custo = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtValor = new javax.swing.JLabel();
        cxValor = new javax.swing.JTextField();
        bntSalvar = new javax.swing.JButton();
        comboProducao = new javax.swing.JComboBox<>();
        comboTipoCusto = new javax.swing.JComboBox<>();
        txtComboProducao = new javax.swing.JLabel();
        txtTipoCusto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCusto = new javax.swing.JTable();
        bntAtualizar = new javax.swing.JButton();
        bntEditar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();

        setClosable(true);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtValor.setText("Valor (R$)");
        jPanel3.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel3.add(cxValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 530, -1));

        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(this::bntSalvarActionPerformed);
        jPanel3.add(bntSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, -1, -1));

        comboProducao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(comboProducao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        comboTipoCusto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(comboTipoCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        txtComboProducao.setText("Produção");
        jPanel3.add(txtComboProducao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtTipoCusto.setText("Tipo de Custo");
        jPanel3.add(txtTipoCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        custo.addTab("Custo", jPanel3);

        tblCusto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCusto);

        bntAtualizar.setText("Atualizar");
        bntAtualizar.addActionListener(this::bntAtualizarActionPerformed);

        bntEditar.setText("Editar");
        bntEditar.addActionListener(this::bntEditarActionPerformed);

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(this::bntExcluirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bntExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntEditar)
                        .addGap(18, 18, 18)
                        .addComponent(bntAtualizar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntEditar)
                    .addComponent(bntAtualizar)
                    .addComponent(bntExcluir))
                .addGap(20, 20, 20))
        );

        custo.addTab("Tabela de Custo", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(custo, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(custo, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        double valor = Double.parseDouble(cxValor.getText().replace(",", "."));

        Producao producao = new Producao();
        ComboItem itemProducao = (ComboItem) comboProducao.getSelectedItem();
        producao.setId(itemProducao.getCodigo());


        TipoCusto tipoCusto = new TipoCusto();
        ComboItem itemTipoCusto = (ComboItem) comboTipoCusto.getSelectedItem();
        tipoCusto.setId(itemTipoCusto.getCodigo());


        Custo c = new Custo();
        c.setValor(valor);
        c.setProducao(producao);
        c.setTipoCusto(tipoCusto);

        boolean retorno = false;

        if (codigo == 0) {
            retorno = cc.salvar(c);
        } else {
            c.setId(codigo);
            retorno = cc.editar(c);
        }

        if (retorno) {
            if (codigo == 0) {
                JOptionPane.showMessageDialog(null, "Salvo com sucesso");
            } else {
                codigo = 0;
                JOptionPane.showMessageDialog(null, "Editado com sucesso");
            }

            cxValor.setText("");
            comboProducao.setSelectedIndex(0);
            comboTipoCusto.setSelectedIndex(0);

        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro, verifique os logs.");
        }

        montaTabela();
    }//GEN-LAST:event_bntSalvarActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        String idString = String.valueOf(tblCusto.getValueAt(tblCusto.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);

        boolean retorno = cc.excluir(id);
        if (retorno) {
            JOptionPane.showMessageDialog(null, "Registro excluído com sucesso!");
            montaTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao excluir!");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        String idString = String.valueOf(tblCusto.getValueAt(tblCusto.getSelectedRow(), 0));
        int id = Integer.parseInt(idString);

        Custo c = cc.recuperarUm(id);
        if (c != null) {
            codigo = c.getId();

            CombosDAO dao = new CombosDAO();

            ComboItem itemProducao = new ComboItem();
            itemProducao.setCodigo(c.getProducao().getId());
            dao.definirItemCombo(comboProducao, itemProducao);

            ComboItem itemTipoCusto = new ComboItem();
            itemTipoCusto.setCodigo(c.getTipoCusto().getId());
            dao.definirItemCombo(comboTipoCusto, itemTipoCusto);

            cxValor.setText(String.valueOf(c.getValor()));

            custo.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao editar!");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_bntEditarActionPerformed

    private void bntAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAtualizarActionPerformed
        montaTabela();        // TODO add your handling code here:
    }//GEN-LAST:event_bntAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAtualizar;
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JComboBox<String> comboProducao;
    private javax.swing.JComboBox<String> comboTipoCusto;
    private javax.swing.JTabbedPane custo;
    private javax.swing.JTextField cxValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblCusto;
    private javax.swing.JLabel txtComboProducao;
    private javax.swing.JLabel txtTipoCusto;
    private javax.swing.JLabel txtValor;
    // End of variables declaration//GEN-END:variables
}
