/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.CadastroSafra;
import view.CadastroProduto;
import view.CadastroProducao;

/**
 *
 * @author henrique
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem8 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        desktopPanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastroProduto = new javax.swing.JMenuItem();
        cadastroProducao = new javax.swing.JMenuItem();
        cadastroSafra = new javax.swing.JMenuItem();
        cadastroCliente = new javax.swing.JMenuItem();
        cadastroTipoProduto = new javax.swing.JMenuItem();

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem8.setSelected(true);
        jCheckBoxMenuItem8.setText("jCheckBoxMenuItem8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPanelLayout = new javax.swing.GroupLayout(desktopPanel);
        desktopPanel.setLayout(desktopPanelLayout);
        desktopPanelLayout.setHorizontalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );
        desktopPanelLayout.setVerticalGroup(
            desktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        cadastroProduto.setText("Cadastro de Produto");
        cadastroProduto.addActionListener(this::cadastroProdutoActionPerformed);
        jMenu1.add(cadastroProduto);

        cadastroProducao.setText("Cadastro de Produção");
        cadastroProducao.addActionListener(this::cadastroProducaoActionPerformed);
        jMenu1.add(cadastroProducao);

        cadastroSafra.setText("Cadastro de Safra");
        cadastroSafra.addActionListener(this::cadastroSafraActionPerformed);
        jMenu1.add(cadastroSafra);

        cadastroCliente.setText("Cadastro Cliente");
        cadastroCliente.addActionListener(this::cadastroClienteActionPerformed);
        jMenu1.add(cadastroCliente);

        cadastroTipoProduto.setText("Cadastro Tipo de Produto");
        cadastroTipoProduto.addActionListener(this::cadastroTipoProdutoActionPerformed);
        jMenu1.add(cadastroTipoProduto);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroProducaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroProducaoActionPerformed
        CadastroProducao cr = new CadastroProducao();
        cr.setVisible(true);
        desktopPanel.add(cr);
    }//GEN-LAST:event_cadastroProducaoActionPerformed

    private void cadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroProdutoActionPerformed
        CadastroProduto cp = new CadastroProduto();
        cp.setVisible(true);
        desktopPanel.add(cp);
    }//GEN-LAST:event_cadastroProdutoActionPerformed

    private void cadastroSafraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroSafraActionPerformed
        CadastroSafra cs = new CadastroSafra();
        cs.setVisible(true);
        desktopPanel.add(cs);
    }//GEN-LAST:event_cadastroSafraActionPerformed

    private void cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClienteActionPerformed
        CadastroCliente cc= new CadastroCliente();
        cc.setVisible(true);
        desktopPanel.add(cc);
    }//GEN-LAST:event_cadastroClienteActionPerformed

    private void cadastroTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroTipoProdutoActionPerformed
        CadastroTipoCusto ctc = new CadastroTipoCusto();
        ctc.setVisible(true);
        desktopPanel.add(ctc);
    }//GEN-LAST:event_cadastroTipoProdutoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastroCliente;
    private javax.swing.JMenuItem cadastroProducao;
    private javax.swing.JMenuItem cadastroProduto;
    private javax.swing.JMenuItem cadastroSafra;
    private javax.swing.JMenuItem cadastroTipoProduto;
    private javax.swing.JDesktopPane desktopPanel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables
}
